from django.urls import path, reverse_lazy
from . import views
from django.contrib.auth.views import PasswordChangeView, PasswordChangeDoneView
from .forms import * 

urlpatterns = [
    path('login/', views.loginPage, name='login'),
    path('change_password/', PasswordChangeView.as_view(template_name='change_password.html',form_class=PasswordChangingForm, success_url=reverse_lazy('password_success')), name='password_change'),
    path('password_success/', PasswordChangeDoneView.as_view(template_name='password_success.html'), name='password_success'),
    path('logout/', views.logoutPage, name='logout'),
    path('', views.index, name='index'),
    path('créer_dwsr/', views.create_dwsr, name='create_dwsr'),
    path('liste_des_dwsr/', views.liste_des_dwsr, name='liste_des_dwsr'),
    path('create_dwsr_user/<int:id>/', views.create_dwsr_user, name='create_dwsr_user'),
    path('liste_des_session/<int:id>', views.liste_session, name='liste_session'),
    path('create_candidat/', views.create_candidat, name='create_candidat'),
    path('liste_des_candidat/', views.liste_des_candidat, name='liste_des_candidat'),
    path('update_candidat/<int:id>', views.update_candidat, name='update_candidat'),
    path('delete_candidat/<int:id>', views.delete_candidat, name='delete_candidat'),
    path('inscrir_dans_session/<int:id>/', views.inscrir_dans_session, name='inscrir_dans_session'),
    path('suprimmer_le_dossier_du_dwsr/<int:id>', views.delete_dwsr, name='delete_dwsr'),
    path('MAJ_du_dossier_du_dwsr/<int:id>', views.update_dwsr, name='update_dwsr'),
    path('liste_des_utilisateur_dnsr/', views.liste_des_user_dnsr, name='liste_des_user_dnsr'),
    path('liste_des_user_dwsr/', views.liste_des_user_dwsr, name='liste_des_user_dwsr'),
    path('liste_des_user_centre/', views.liste_des_user_centre, name='liste_des_user_centre'),
    path('liste_des_user_candidat/', views.liste_des_user_candidat, name='liste_des_user_candidat'),
    path('profile_candidat/<int:id>', views.profile_candidat, name='profile_candidat'),
    path('create_candidat_user/<int:id>', views.create_candidat_user, name='create_candidat_user'),
    path('saisir_résultat/<int:id>', views.saisir_résultat, name='saisir_résultat'),
    path('delete_user_dnsr/<int:id>', views.delete_user_dnsr, name='delete_user_dnsr'),
    path('update_user_dnsr/<int:id>', views.update_user_dnsr, name='update_user_dnsr'),
    path('delete_user_dwsr/<int:id>', views.delete_user_dwsr, name='delete_user_dwsr'),
    path('update_user_dwsr/<int:id>', views.update_user_dwsr, name='update_user_dwsr'),
    path('delete_user_centre/<int:id>', views.delete_user_centre, name='delete_user_centre'),
    path('update_user_centre/<int:id>', views.update_user_centre, name='update_user_centre'),
    path('delete_user_candidat/<int:id>', views.delete_user_candidat, name='delete_user_candidat'),
    path('update_user_candidat/<int:id>', views.update_user_candidat, name='update_user_candidat'),
    path('créer_centre_examen/', views.create_centre, name='create_centre'),
    path('liste_des_centre_examens/', views.liste_centre_examens, name='liste_centre_examens'),
    path('create_centre_user/<int:id>', views.create_centre_user, name='create_centre_user'),
    path('update_centre/<int:id>', views.update_centre, name='update_centre'),
    path('delete_centre/<int:id>', views.delete_centre, name='delete_centre'),
    path('create_auto_ecole/', views.create_auto_ecole, name='create_auto_ecole'),
    path('liste_auto_ecole/', views.liste_auto_ecole ,name='liste_auto_ecole'),
    path('update_auto_ecole/<int:id>', views.update_auto_ecole, name='update_auto_ecole'),
    path('delete_auto_ecole/<int:id>', views.delete_auto_ecole, name='delete_auto_ecole'),
    path('create_examinateur/', views.create_examinateur, name='create_examinateur'),
    path('liste_examinateur/', views.liste_examinateur, name='liste_examinateur'),
    path('update_examinateur/<int:id>', views.update_examinateur, name='update_examinateur'),
    path('delete_examinateur/<int:id>', views.delete_examinateur, name='delete_examinateur'),
    path('calendrier_des_session/', views.session_calendar, name='session_calendar'),
    path('ajouter une session/', views.add_session, name='add_session'),
    path('imprimer_liste_des_session/', views.render_pdf_view, name='liste_des_session_pdf'),
    path('liste_centre_examens/', views.liste_des_centre, name='liste_des_centre'),
    path('votre_profile/', views.profile_candidat_candidat, name='profile_candidat_candidat'),
    path('imprimer_convocation/', views.render_pdf_convocation, name='print_convocation'),
    path('statistique_dwsr/<int:id>', views.consulter_stat_dwsr, name='consulter_stat_dwsr'),
    path('statistiques_du_auto_école/<int:id>', views.consulter_stat_auto_ecole, name='consulter_stat_auto_ecole'),
    path('liste_des_sessions_pour_de_ce_centre/', views.liste_des_sessions_pour_centre, name='liste_des_sessions_pour_centre'),
    path('supprimer_cette_session/<int:id>', views.delete_this_session, name='delete_this_session'),
]