# Generated by Django 4.0.4 on 2022-06-01 20:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0021_alter_candidat_date_de_dossier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidat',
            name='date_de_dossier',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 1, 22, 38, 33, 19262)),
        ),
        migrations.RemoveField(
            model_name='session',
            name='centre_examen',
        ),
        migrations.AddField(
            model_name='session',
            name='centre_examen',
            field=models.ManyToManyField(to='compte.centreexamen'),
        ),
    ]
