# Generated by Django 4.0.4 on 2022-06-01 20:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0022_alter_candidat_date_de_dossier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidat',
            name='date_de_dossier',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 1, 22, 45, 3, 56369)),
        ),
        migrations.RemoveField(
            model_name='session',
            name='centre_examen',
        ),
        migrations.AddField(
            model_name='session',
            name='centre_examen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='compte.centreexamen'),
        ),
    ]
