# Generated by Django 4.0.4 on 2022-06-05 14:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0023_alter_candidat_date_de_dossier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidat',
            name='réusit',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='date_de_dossier',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 5, 16, 12, 43, 338834)),
        ),
    ]
