# Generated by Django 4.0.4 on 2022-06-05 14:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0024_candidat_réusit_alter_candidat_date_de_dossier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidat',
            old_name='réusit',
            new_name='réussit',
        ),
        migrations.AlterField(
            model_name='candidat',
            name='date_de_dossier',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 5, 16, 13, 5, 133832)),
        ),
    ]
